language: php

php:
  - 7.2
  - 7.3

addons:
  chrome: stable

services:
  - xvfb

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - ./vendor/bin/dusk-updater update
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
